### ISSUE TITLE
Providing callback option when user choose Don't Allow for permission

### ISSUE THREAD

**Issue by sunkibaek** [marcshilling/react-native-image-picker#349] opened 2016-10-05 09:13 UTC
I would like to direct users to settings when they try to open image picker after they choose not to allow Photos for our app. To implement this, I can check if response object has `error` key or not. So far so good.

But the problem is the response object will have the same `error` key when user choose `Don't Allow` when they are prompted with permission alert box for the first time.

I can save the state internally in our app if the user has been offered the alert box or not but I was just wondering if it would be possible for `showImageAllow` to accept the third callback that will be run when user chooses `Don't Allow` in permission alert box.

**Comment by marcshilling** [comment] 2016-10-12 13:49
Duplicate of #330. I don't have time to work on this at the moment, so a PR would be nice, but I'll get around to it eventually.

**Closed by marcshilling** 2016-10-12 13:49 UTC
Labels: feature request
