### ISSUE TITLE
Unfortunately ,Gallery has stopped

### ISSUE THREAD

**Issue by wzy535** [marcshilling/react-native-image-picker#300] opened 2016-09-01 06:18 UTC
Hi,
In android genymotion, I got this error when I click 'Choose from library...'. bellow is the adb logcat 
<a href="http://www.saitio.com/images/logcat.txt">logcat</a>

Please help, thank you very much!

**Comment by yfuks** [comment] 2016-09-01 11:07
Can you reproduce the issue when pressing gallery in your android native menu ?

**Comment by reyesreg** [comment] 2016-09-01 12:35
Same issue with me. It's a problem with Genymotion because it works fine with my Android device. :)

**Comment by priezz** [comment] 2016-09-03 12:55
I have this issue both in Genymotion and on the real device - when the photo from camera or from the gallery is chosen the app crashes.. Android 6.0, RN 0.33

**Comment by yfuks** [comment] 2016-09-05 15:59
Make sure you followed all the INSTALL steps in the README and if you still get the issue please copy past your stack trace error

**Comment by priezz** [comment] 2016-09-05 16:11
Yes, I have followed all the steps. I can't copy the stacktrace as the app just crashes with no logs (I use `react-native log-android` for logging). Is there a way to get more information in the crash?
Just for comparison - the crop-picker library works fine in the same conditions.

**Comment by marcshilling** [comment] 2016-09-08 19:49
I can't reproduce this by running the Example project on a Galaxy S6 Android 6.0.1.

**Comment by azaleas** [comment] 2016-09-15 05:46
Any luck on this issue? I tried using Android Studio Emulator. There Gallery opens but once I pick an image app crashes. On Genymotion app crashes, but due to Gallery crash. 

This is the log for Genymotion:

**09-15 01:33:24.472  5839  5852 E AndroidRuntime: FATAL EXCEPTION: GLThread 175
09-15 01:33:24.472  5839  5852 E AndroidRuntime: Process: com.android.gallery3d, PID: 5839
09-15 01:33:24.472  5839  5852 E AndroidRuntime: java.lang.IllegalArgumentException: No config chosen
09-15 01:33:24.472  5839  5852 E AndroidRuntime: 	at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:870)
09-15 01:33:24.472  5839  5852 E AndroidRuntime: 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
09-15 01:33:24.472  5839  5852 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
09-15 01:33:24.472  5839  5852 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)**

This is the log for Android Studio Emulator:

**09-15 08:43:40.031  2714  2714 E AndroidRuntime: FATAL EXCEPTION: main
09-15 08:43:40.031  2714  2714 E AndroidRuntime: Process: com.rn_sample_app, PID: 2714
09-15 08:43:40.031  2714  2714 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:612)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6428)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-15 08:43:40.031  2714  2714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)**

**Comment by georgi-kovachev** [comment] 2016-09-19 14:19
My android app is also crashed with no error.
I am using Android 5.0
and react native 0.33.
It doesn't provide any log.

**Comment by Alternhuman** [comment] 2016-09-23 11:43
Same issue here, both on an emulator and a Moto G running Android 5.1. React Native version 0.33. It crashes when selecting an image from the gallery or taking a picture from the camera, as well as cancelling those in the middle of the process. The stacktrace that I got from `adb logcat` is the following:

```
09-23 13:36:26.409  5868  5868 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:612)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.demo.demo.MainActivity.onActivityResult(MainActivity.java:25)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.Activity.dispatchActivityResult(Activity.java:6428)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.ActivityThread.-wrap16(ActivityThread.java)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.os.Handler.dispatchMessage(Handler.java:102)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.os.Looper.loop(Looper.java:148)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at java.lang.reflect.Method.invoke(Native Method)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-23 13:36:26.409  5868  5868 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-23 13:36:26.412  1574  2029 W ActivityManager:   Force finishing activity
```

I have tested the code on iOS successfully, it is pretty much the same as the sample code:

```jsx
const imagePickerOptions = {
      mediaType: 'photo',
    };
    ImagePicker.showImagePicker(imagePickerOptions, (response) => {
      if(response.error){
        console.warn(response.error);
      }
      else if(!response.didCancel){
        const picture = {uri: `data:image/jpeg;base64,${response.data}`, isStatic: true};
        this.setState({picture});
      }
    });
```

**Comment by georgi-kovachev** [comment] 2016-09-25 14:26
any updates on this issue?

**Comment by yfuks** [comment] 2016-09-25 20:49
```java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"```
- Make sure you update this project package
- Make sure you folow all the instalations steps in the README
- then : #308

**Comment by georgi-kovachev** [comment] 2016-09-25 21:47
hi @yfuks which file is that?

**Comment by nodegin** [comment] 2016-09-26 08:59
facing the same error here, but fixed by upgrading to v0.22.8

**Comment by georgi-kovachev** [comment] 2016-09-26 09:02
@nodegin I think latest version is 0.22.7. 
how can I get 0.22.8?

**Comment by nodegin** [comment] 2016-09-26 10:30
@georgi-kovachev just check it on npm, it says that the latest one is 0.22.8

**Comment by georgi-kovachev** [comment] 2016-09-26 11:46
@nodegin i see. i am checking from github.
https://github.com/marcshilling/react-native-image-picker/blob/master/package.json
Thanks I will try to use with 0.22.8

**Comment by marcshilling** [comment] 2016-10-03 14:58
This issue is kind of outdated at this point so I'm going to close. Please open another if anyone is still having issues on the latest version.

**Closed by marcshilling** 2016-10-03 14:58 UTC
