### ISSUE TITLE
Base64 No longer works. All image filenames seem to come in as GIF

### ISSUE THREAD

**Issue by sgonyea** [marcshilling/react-native-image-picker#108] opened 2016-02-14 05:20 UTC
It looks like the original "add GIF support" PR went through several mutations.  I was trying to break down the changes, haven't had a ton of luck yet.

I can't even seem to get images taken through the Camera to display. I'm super confused as to why it's no longer working.

**Comment by JorritPosthuma** [comment] 2016-02-14 19:20
I am having the exact same issue 😅, have you found a workaround?

**Comment by yfuks** [comment] 2016-02-14 22:44
The **PR** is in 0.13.0...
```
$> npm install react-native-image-picker@0.12.4
```

I don't think it's a great thing to do.. but that can fix the issue for the moment

**Comment by marcshilling** [comment] 2016-02-14 22:58
I can't fix this right now but will tomorrow. The issue is with the most recent PR. search gif in the iOS code and you should see the issue pretty easily. Will accept PR if someone wants to send.

**Comment by JorritPosthuma** [comment] 2016-02-14 23:16
No hurry! And complements for the awesome plugin ☺️. I'm currently also not
able to fix directly.

**Comment by marcshilling** [comment] 2016-02-15 15:27
Fixed in `0.14.2` on npm. Sorry about that! My fault for not testing PRs before accepting :)

**Closed by marcshilling** 2016-02-15 15:27 UTC
