### ISSUE TITLE
[Android] Crash after choosing a photo.

### ISSUE THREAD

**Issue by dhrrgn** [marcshilling/react-native-image-picker#166] opened 2016-04-06 14:30 UTC
We are seeing quiet a lot of crashes due to the image picker on Android.  Here is the Exception/Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://media/external/images/media/7396 flg=0x1 }} to activity {com.tackk.squad/com.tackk.squad.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3974)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4017)
       at android.app.ActivityThread.access$1400(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:504)
       at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:388)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:188)
       at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:597)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:180)
       at android.app.Activity.dispatchActivityResult(Activity.java:6475)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3970)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4017)
       at android.app.ActivityThread.access$1400(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Here are the options we are using:

```
    {
      cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Take Photo...',
      chooseFromLibraryButtonTitle: 'Choose from Library...',
      cameraType: 'back',
      noData: true,
      quality: 0.5,
    }
```

**Comment by marcshilling** [comment] 2016-04-06 14:35
Duplicate of #165

**Closed by marcshilling** 2016-04-06 14:35 UTC

**Comment by dhrrgn** [comment] 2016-04-06 14:39
Ah, my bad, missed that, sorry.
