### ISSUE TITLE
image chosen from 'My photo stream' displayed as empty

### ISSUE THREAD

**Issue by pgmemk** [marcshilling/react-native-image-picker#8] opened 2015-07-17 18:42 UTC
Great component. I am trying to use it in our open source chat app. 
It works great if the image was chosen from anything other then 'My Photo Stream'. The same image in 'My photo stream' and in 'Camera Roll' has different url. And the 'Camera Roll' one works fine.

**Comment by darkrishabh** [comment] 2015-07-21 05:18
@pgmemk I just tested this. And it works just fine. What is your iOS version and phone?

**Comment by marcshilling** [comment] 2015-08-18 18:02
I also can't reproduce. Are you still having this problem @pgmemk?

**Comment by darkrishabh** [comment] 2015-08-19 23:04
@pgmemk there can be an issue displaying the image. I have also sometimes ran into this issue where you might have to add {width, height} in the style. Please try that and also console.log the URL of the image that you select and if there is a URL then there should be an image. 

Developing is all about debugging. Try setting a breakpoint in the code at line # 93 in UIImagePickerManager.m and watch the UIImage variable. You can view the image also if you click on an eye icon[if you can't find it, then google it]. Remember to use URI output and not Base64 i.e setting the "returnBase64Image" key to be false [default] in your component config options.

So all you need to try are 3 things now,
1. check if you are getting a URL by console.log
2. Try adding width and height also flex(play with the stylesheet a bit, maybe that helps)
3. Debug using breakpoint in the Obj-C code itself.

let us know if this helps.

**Comment by marcshilling** [comment] 2015-09-17 21:32
Closing this. Lots of changes since this issue was opened. Feel free to open a new one if you're still having problems.

**Closed by marcshilling** 2015-09-17 21:32 UTC
