### ISSUE TITLE
Stop running cut while taking the photo camera

### ISSUE THREAD

**Issue by mvpdream** [marcshilling/react-native-image-picker#189] opened 2016-04-28 05:05 UTC
this is my options
var options = {
      title: '选择图片',
      cancelButtonTitle: '取消',
      takePhotoButtonTitle: '拍照',
      chooseFromLibraryButtonTitle: '从图库中获取',
      maxWidth: 500,
      maxHeight: 500,
      aspectX: 1,
      aspectY: 1,
      quality: 1,
      allowsEditing: true,
    };

**Comment by yfuks** [comment] 2016-04-28 10:23
Are you sure it's not a duplicate of #177 ?

**Comment by mvpdream** [comment] 2016-04-29 05:22
But made no mention of the solution

**Comment by yfuks** [comment] 2016-04-29 10:21
Duplicate of #177

**Closed by yfuks** 2016-04-29 10:21 UTC
