### ISSUE TITLE
App crash after using camera picker

### ISSUE THREAD

**Issue by radko93** [marcshilling/react-native-image-picker#291] opened 2016-08-22 14:26 UTC
1. Make a new picture.
2. App crashes after confirmation.

Correct image is sent to JS code even after app crash. This is not happening when using a picture from gallery. In the `onActivityResult` the `data` parameter is null.

I'm getting this on crash:
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.app/com.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference`

RN 0.32.0-rc, Android 6.0.1.
Picker options:
```
const options = {
  title: 'Select Image',
  storageOptions: {
    skipBackup: true,
    path: 'images',
  },
};
```

**Comment by yfuks** [comment] 2016-09-05 15:54
Hi,

Seems like a concurrent request crash the app before the actual picker request.
```result=-1``` is an Activity ```RESULT_OK``` looks strange to me.
I will add a check on the ```data=null``` then.

Thanks for the debug!

Sorry for the late response.

**Comment by marcshilling** [comment] 2016-09-08 21:11
Can you confirm that this is still happening on `v0.22.2`?

**Comment by radko93** [comment] 2016-09-19 11:42
Will go back to this issue if I find some more time, sorry!

**Comment by AlexSchwabauer** [comment] 2016-09-20 13:08
Hi, the problem is that the module uses

` static final int REQUEST_LAUNCH_IMAGE_CAPTURE = 1;
  static final int REQUEST_LAUNCH_IMAGE_LIBRARY = 2;
  static final int REQUEST_LAUNCH_VIDEO_LIBRARY = 3;
  static final int REQUEST_LAUNCH_VIDEO_CAPTURE = 4;
`
in ImagePickerModule.

You should use more random ints so other activityListeners will not crash the app. If another module uses the same requestcodes, the app will most likely crash.

**Comment by yfuks** [comment] 2016-09-20 13:22
We probably just need to add ```mCallback = null;```
after [line 446](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L446)

**Comment by marcshilling** [comment] 2016-09-28 16:13
This should be fixed now. I made the activity request codes more unique.

**Closed by marcshilling** 2016-09-28 16:13 UTC
