### ISSUE TITLE
How to customize button's wordings when editing image?

### ISSUE THREAD

**Issue by livoras** [marcshilling/react-native-image-picker#294] opened 2016-08-25 06:21 UTC
When editing image, button shown on the bottom are 'Cancel' and 'Choose'. How to customize the wordings of them and also the buttons when taking photo.

**Comment by marcshilling** [comment] 2016-08-25 14:19
This is kind of a duplicate of #150, so read the comments there. Basically, those are native iOS strings. They can be changed with localization settings.

**Closed by marcshilling** 2016-08-25 14:19 UTC
