### ISSUE TITLE
Returning some kind of code when permission is not granted.

### ISSUE THREAD

**Issue by ptfly** [marcshilling/react-native-image-picker#529] opened 2017-03-29 11:20 UTC
It will be nice to have a solid approach when handling this particular error. Currently (at least on iOS) it returns a simple message like: `Camera permissions not granted` or `Photo library permissions not granted`. Instead of just this, it will be much better to have a code or similar, based on which my app can show something more helpful to the user, like how to give permissions back, etc. Right now I have to match string within the error in order to handle that permission case.

P.S. Thanks for the plugin, much appreciated!

**Comment by marcshilling** [comment] 2017-03-29 17:01
Duplicate of #330. Agree that it needs to be implemented I just haven't gotten around to it. PR's would be welcome.

**Closed by marcshilling** 2017-03-29 17:01 UTC
