### ISSUE TITLE
Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by fwang** [marcshilling/react-native-image-picker#333] opened 2016-09-23 18:22 UTC
When I install 0.22.8 via npm, ImagePickerModule.java line 61~64 are

**static final int REQUEST_LAUNCH_IMAGE_CAPTURE = 813881;
static final int REQUEST_LAUNCH_IMAGE_LIBRARY = 813882;
static final int REQUEST_LAUNCH_VIDEO_LIBRARY = 813883;
static final int REQUEST_LAUNCH_VIDEO_CAPTURE = 813884;**

When I install 0.22.7 via npm, it is

**static final int REQUEST_LAUNCH_IMAGE_CAPTURE = 1;
static final int REQUEST_LAUNCH_IMAGE_LIBRARY = 2;
static final int REQUEST_LAUNCH_VIDEO_LIBRARY = 3;
static final int REQUEST_LAUNCH_VIDEO_CAPTURE = 4;**

Because the RequestCode is larger than a 16bit integer in 0.22.8, error is thrown. Also, I downloaded the 0.22.8 release through github, and it seems fine.

**Comment by marcshilling** [comment] 2016-09-23 19:03
I'm confused. You say an error is thrown because they are larger than 16bit ints but then you say that "it seems fine". I just ran the example project with no problems. What exactly is your issue?

**Comment by fwang** [comment] 2016-09-23 19:23
Sorry for the confusion.

When I download the 0.22.8 release zip file from github, the final int are 1, 2, 3, 4. But when I npm install the 0.22.8 version, the final int are  813881 ~ 813884.

Npm installing 0.22.7 is fine.

**Comment by marcshilling** [comment] 2016-09-23 19:29
`v0.22.8` is the latest version and the ints should be the big numbers. I made that change yesterday and it works fine for me. I don't see any indication about them being 16bit ints. They are 32 as far as I can tell. Where are you getting this info?

**Comment by DanielMaly** [comment] 2016-09-28 10:28
I'm getting this: 

> 09-28 12:26:10.660 6878-6917/com.sanofibabyfe E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                Process: com.sanofibabyfe, PID: 6878
                                                                java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
                                                                    at android.support.v4.app.BaseFragmentActivityEclair.checkForValidRequestCode(BaseFragmentActivityEclair.java:64)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:868)
                                                                    at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:289)
                                                                    at com.imagepicker.ImagePickerModule$2.onClick(ImagePickerModule.java:158)
                                                                    at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
                                                                    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                    at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
                                                                    at android.widget.AbsListView$3.run(AbsListView.java:3879)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by marcshilling** [comment] 2016-09-28 16:09
Allllrighty then, even though I can't reproduce this I guess I'll change the request codes (again)...give me a minute.

**Comment by marcshilling** [comment] 2016-09-28 16:12
Should be fixed in `v0.22.9`! Thanks for making me aware of this.

**Closed by marcshilling** 2016-09-28 16:12 UTC

**Comment by fwang** [comment] 2016-09-28 21:00
Sorry for the late reply. Yes I was getting the same error as @DanielMaly.

Thanks for the fix!
